# Generated by Django 5.1.14 on 2026-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='transcription_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Deepgram'), (2, 'Closed Caption From Platform'), (3, 'Gladia'), (4, 'OpenAI'), (5, 'Assembly AI'), (6, 'Sarvam'), (7, 'ElevenLabs'), (8, 'Kyutai'), (9, 'Custom Async'), (10, 'Custom Async v2'), (11, 'No Transcription')], null=True),
        ),
    ]
